### ISSUE TITLE
Use git submodule or subtree for secp256k1

### ISSUE THREAD

**Issue by Sjors** [ElementsProject/libwally-core#101]
It's currently non-trivial to verify that the code in `src/secp256k1` matches upstream. A git submodule or subtree is probably the simplest way to fix that. If you need any patches, have a script apply those.

See also #11 which goes further and argues for completely removing it in favor of a system library, but that doesn't seem practical.

There may be other solutions.

**Comment by benma** [comment]
Seconded. We make use of libwally-core in the bitbox02 firmware, and it would make it easier for us if we could include our fork of secp256k1. A build option to link to a custom lib would be ideal. A submodule is a good start.

**Comment by benma** [comment]
@greenaddress would you be able to do the submodule soon? It should be straight forward - make a repo with a branch at the right upstream commit, apply the two patches, and add it as a submodule. It would make it a lot easier for me to apply our own patches in the BitBox02.

I can also prepare the PR if you prefer, but the secp256k1 fork should be under your control (e.g. at https://github.com/ElementsProject/libwally-core-secp256k1), so it's probably quicker for you to do the whole thing.

**Comment by reardencode** [comment]
Ideally, I think that wally should be able to link to a provided libsecp256k1. Moving to a submodule is a stepping stone in that direction.

**Comment by jgriffiths** [comment]
Per the linked PR above, the latest updates to secp mean we don't need our patches any more, so we can use a submodule.

**Comment by jgriffiths** [comment]
libsecp as a submodule has been merged into master, closing.
