### ISSUE TITLE
Derive address from BIP32 extended key

### ISSUE THREAD

**Issue by Sjors** [ElementsProject/libwally-core#102]
A good approach could be a variant on [wally_wif_to_address](https://wally.readthedocs.io/en/release_0.7.0/address/#c.wally_wif_from_bytes):

```c
int wally_addr_from_bip32_key(const struct ext_key *hdkey, const char *addr_family,\
                              uint32_t flags, char **output)
```

Where `flags` indicate the address type (legacy, native segwit, p2sh-segwit).

Most of the implementation can be borrowed from c-lightning, in particular [encode_pubkey_to_addr](https://github.com/ElementsProject/lightning/blob/11412435ce0cae92205178db9a9f4b64d0d78830/wallet/walletrpc.c#L200-L248) which uses a [pubkey straight from ext_key](https://github.com/ElementsProject/lightning/blob/master/wallet/walletrpc.c#L319-L336).

**Comment by greenaddress** [comment]
I think this is implemented now, closing the issue, feel free to reopen otherwise.
