### ISSUE TITLE
Derive scriptPubKey from BIP32 key

### ISSUE THREAD

**Issue by Sjors** [ElementsProject/libwally-core#117]
Similar to #103, but it would produce bytes containing the `scriptPubKey`.

This is useful when composing a transaction, to directly generate a change output. Otherwise you have to derive a change address with `wally_bip32_key_to_address` / `wally_bip32_key_to_addr_segwit` and then parse it with `wally_addr_segwit_to_bytes` / `wally_address_to_scriptpubkey` (#112)

**Comment by jgriffiths** [comment]
I think descriptors are the best way to accomplish this now that they are merged.

Given a (reusable) descriptor string such as `"p2pkh(key)"` and an input variable map of `"key"` -> `"xpub..."` from the bip32 key, both an address and scriptpubkey can be generated. This is assuming of course that the bip44 style descriptor and the root key aren't sufficient for some reason.
