### ISSUE TITLE
build pip wheels with anylinux

### ISSUE THREAD

**Issue by greenaddress** [ElementsProject/libwally-core#128]
wally provides python bindings and provides binary version of these python bindings with wally - however IIRC these can't be uploaded to pip as they don't follow the ```anylinux``` build requirements. IIRC this is related to glibc versions.

Wally pip wheels should be ```anylinux``` or ```manylinux``` compatible - https://www.python.org/dev/peps/pep-0571/

**Comment by tiero** [comment]
It's possible to compile the wheel for `armv7l` archs mounted on ODroid etc?

**Comment by jgriffiths** [comment]
Closing as https://github.com/ElementsProject/libwally-core/pull/246 provides manylinux support once merged.
