### ISSUE TITLE
How to create a transaction for issuing an asset

### ISSUE THREAD

**Issue by altafan** [ElementsProject/libwally-core#138]
I'm trying to create a transaction for issuing an asset using the Python wrapper of libwally.
For my test, I'm creating a transaction with just 1 input and 2 outputs like the following:
```
def build_tx(prev_tx_hash, prev_tx_index, seq, issuance_entropy, issuance_amount, ...):
   tx = wally.tx_init(2, 0, 1, 2)
   wally.tx_add_elements_raw_input(
            tx,
            prev_tx_hash,
            prev_tx_index,
            seq, # sequence
            None, # scriptsig, is calculated later
            None, # witness
            None, # nonce
            issuance_entropy, # entropy
            issuance_amount, # issuance_amount
            None, # inflation_keys
            None, # issuance_amount_rangeproof
            None, # issuance_rangeproof
            None, # pegin_witness
            0 # flags, must be zero
   )
   print(wally.hex_from_bytes(wally.tx_get_input_entropy(tx, 0)))

   # add outputs
   [ ... ]

   return wally.tx_to_hex(tx, 0)
```
When I test this function it actually prints the same entropy I'm passing for the input and returns the hex of the unsigned transaction.

However, when decoding the transaction with `liquid-cli decoderawtransaction`, I see from the JSON that the input misses the *issuance* part.

The same happens using libwally with `tx_from_bytes(...)` and then printing again `wally.tx_get_input_entropy(tx, 0)`, now it's 0, thus I'm quite sure I'm using the wrong flag when returning the serialized transaction but I did not find any example of this in this repo.

**Comment by altafan** [comment]
I'm not sure I got you, but my problem is not with the entropy itself, but rather with the serialization of the transaction: I'm sure the input has `issuance_entropy`  and `issuance_amount` set, but after serializing the transaction they are set to 0, thus I'm "loosing" data in some way.

**Comment by altafan** [comment]
Both ways return the same raw transaction, but It seems to be serialized in the wrong way.
This is what I'm doing by not using the *raw* wally method:

```
def build_tx(prev_tx_hash, prev_tx_index, seq, issuance_entropy, issuance_amount, ...):
   tx = wally.tx_init(2, 0, 1, 2)
   tx_input = wally.tx_elements_input_init(
            prev_tx_hash,
            prev_tx_index,
            seq, # sequence
            None, # scriptsig, is calculated later
            None, # witness
            None, # nonce
            issuance_entropy, # entropy
            issuance_amount, # issuance_amount
            None, # inflation_keys
            None, # issuance_amount_rangeproof
            None, # issuance_rangeproof
            None, # pegin_witness
   )
   wally.tx_add_input(tx, tx_input)
   # add outputs
   [ ... ]

   return wally.tx_to_hex(tx, 0)
```

The raw transaction looks like:

```
0200000000018ccaf013fb00eaa3f1ebdf6cef1815319d9b3944ec993e6c5425c2d89a025fbf0000008000ffffffff0000000000000000000000000000000000000000000000000000000000000000f34534a4487cc058debdf55e8e6d32ac435b18c3737550fd74411a94a283dce0174876e80000020125b251070e29ca19043cf33ccd7324e2ddab03ecc4ae0b5e77c4fc0e5cf6c95a0100000000000000ec00000125b251070e29ca19043cf33ccd7324e2ddab03ecc4ae0b5e77c4fc0e5cf6c95a0100000002540be314001976a91450a410115f0a7d8a99472e47d1928ff8086948c888ac
```

If I pass `None` istead of `issuance_entropy` then it's serialized in a good way, but again the input has no issuance data.

```
0200000000018ccaf013fb00eaa3f1ebdf6cef1815319d9b3944ec993e6c5425c2d89a025fbf0000000000ffffffff020125b251070e29ca19043cf33ccd7324e2ddab03ecc4ae0b5e77c4fc0e5cf6c95a01000000000000006800000125b251070e29ca19043cf33ccd7324e2ddab03ecc4ae0b5e77c4fc0e5cf6c95a0100000002540be398001976a91450a410115f0a7d8a99472e47d1928ff8086948c888ac00000000
```

Can you provide an example of how to do this in the right way?
It could be useful for everyone since it seems that there are no examples/tests of this in the repo.

**Comment by glslang** [comment]
you need to do (prev_tx_index | 1 << 31) as per the comments above. we have a MR for pegins which will demonstrate this but issuance follow the same pattern.

**Comment by glslang** [comment]
A quick and dirty example would be
```
import wallycore as wally

issuance_amount = wally.tx_confidential_value_from_satoshi(10000)
zeroes = wally.hex_to_bytes('00'*32)
txhash = wally.hex_to_bytes('11'*32)
entropy = wally.hex_to_bytes('22'*32)
vout = 0

tx = wally.tx_init(2, 0, 1, 2)
wally.tx_add_input(tx, wally.tx_elements_input_init(txhash, vout,
                                                    0xffffffff,
                                                    None, None,
                                                    None, entropy,
                                                    issuance_amount,
                                                    None, None, None))

wally.tx_add_output(tx, wally.tx_elements_output_init(None, None, issuance_amount, None, None, None))

print(wally.tx_to_hex(tx, 0))
```

**Comment by altafan** [comment]
I successfully issued an asset with a transaction built and signed with libwally, finally!
Thank you for your support.
This can be closed, to me.
