### ISSUE TITLE
Some `wally_tx_*` calls overreact if the caller tries to be helpful and hints with `WALLY_TX_FLAG_USE_ELEMENTS`

### ISSUE THREAD

**Issue by cdecker** [ElementsProject/libwally-core#139]
Some calls, e.g., `wally_tx_get_length`, will fail if we specify that we use elements when calling them, leading the caller to have to mask out the bits in the call.

An example of this can be found here:

https://github.com/ElementsProject/lightning/blob/22ea458298238dcf23dfb1dffae9ad8b9725b94b/bitcoin/tx.c#L325-L329

It'd be nice to perform this masking inside the function itself, in order to expose a more consistent interface. It could also verify that the flag matches with the internal detection of elements transactions and return an error if they don't match (though that'd be a breaking API change).

**Comment by jgriffiths** [comment]
Rejecting rather than ignoring this flag was a mistake, fixed in #210.
