### ISSUE TITLE
Output descriptor parsing

### ISSUE THREAD

**Issue by Sjors** [ElementsProject/libwally-core#151]
Bitcoin Core introduced Output Descriptors recently: https://github.com/bitcoin/bitcoin/blob/master/doc/descriptors.md

They're quite useful, but there's no BIP. So perhaps it's premature to implement. But if so, I'd like to see a method that takes a descriptor string and an index as input, and returns an address (like the [deriveaddresses](https://bitcoincore.org/en/doc/0.19.0/rpc/util/deriveaddresses/) RPC). 

E.g. from one of the Bitcoin Core examples:

```
Inputs:
* Descriptor: 
wsh(multi(1,xpub661MyMwAqRbcFW31YEwpkMuc5THy2PSt5bDMsktWQcFF8syAmRUapSCGu8ED9W6oDMSgv6Zz8idoc4a6mr8BDzTJY47LJhkJ8UB7WEGuduB/1/0/*,xpub69H7F5d8KSRgmmdJg2KhpAK8SR3DjMwAdkxj3ZuxV27CprR9LgpeyGmXUbC6wb7ERfvrnKZjXoUmmDznezpbZb7ap6r1D3tgFxHmwMkQTPH/0/0/*))#t2zpj2eu
* Index: 0

Output:
* Address: bc1qvjtfmrxu524qhdevl6yyyasjs7xmnzjlqlu60mrwepact60eyz9s9xjw0c
```

For better performance it could take an array of indices to calculate an array of addresses, or it could output a cache that the consuming application can hold on to (that's what Bitcoin Core does).

**Comment by jgriffiths** [comment]
Implemented in https://github.com/ElementsProject/libwally-core/pull/310, please comment there if you would, thanks.
