### ISSUE TITLE
PSBT missing docs 

### ISSUE THREAD

**Issue by Sjors** [ElementsProject/libwally-core#152]
The new PSBT methods seem to have code documentation, but they're not showing up at https://wally.readthedocs.io/en/release_0.7.5

It might be a matter of adding "psbt" here:
https://github.com/ElementsProject/libwally-core/blob/d0a13e08b51fccf420e2be255e3c959831637aef/docs/source/conf.py#L56-L59

cc @achow101

**Comment by greenaddress** [comment]
this is merged now, closing manually
