### ISSUE TITLE
bip32_key_init_alloc -> depth should be uint8_t, not uint32_t?

### ISSUE THREAD

**Issue by benma** [ElementsProject/libwally-core#165]
depth is declared as uint8_t in the struct:

https://github.com/ElementsProject/libwally-core/blob/master/include/wally_bip32.h#L47

bip32_key_init_alloc's arg is uint32_t:

https://github.com/ElementsProject/libwally-core/blob/master/src/bip32.c#L619

There is no check on the range and the struct field is set directly:

https://github.com/ElementsProject/libwally-core/blob/master/src/bip32.c#L659

Should the arg type be changed to uint8_t?

**Comment by glslang** [comment]
Thank you for this. I kept the arg type as uint32_t to maintain binary compatibility and to simplify the bindings (primarily java), but added a range check.
