### ISSUE TITLE
bip32: proposal to rename parent160 to parent_fingerprint, and shrink it to 4 bytes

### ISSUE THREAD

**Issue by benma** [ElementsProject/libwally-core#166]
The current bip32 API stores 20 bytes for the parent hash, but only ever uses the first four bytes as the fingerprint.

This makes functions like `bip32_key_init_alloc()` awkward to use, as it takes 20 bytes for the parent, but if you only have data from an xpub, there are only 4 bytes available.

It would also get rid of this inconsistent state:

https://github.com/ElementsProject/libwally-core/blob/895632cb002203d30272c8c0f11d3060f3b2c54a/src/bip32.c#L304-L307

Thoughts?

**Comment by jgriffiths** [comment]
Hi @benma, I have taken the approach of allowing 4 byte fingerprints to be passed if the full parent hash isn't available/desired. This keeps binary compatibility and allows use of the parent hash as more than a simple hint while supporting the 4 byte fingerprint.

Once this is merged and you update you can remove the final quirk from `apps_common_bip32_xpub_from_protobuf` in bitbix02-firmware by simply passing `xpub_in->parent_fingerprint, sizeof(xpub_in->parent_fingerprint)` directly.

**Comment by jgriffiths** [comment]
Merged following code review, closing.

**Comment by benma** [comment]
Excellent! Thank you.
