### ISSUE TITLE
script: multisig cosigner limit is 16, should be 15?

### ISSUE THREAD

**Issue by benma** [ElementsProject/libwally-core#170]
https://github.com/ElementsProject/libwally-core/blob/2a7c2739efde5094bac35b42910af1e670ca6d75/src/script.c#L562

I am unsure why 16 cosigners are allowed, as only up to 15 can be safely used in P2SH. Is this a typo? The unit tests do not cover the upper limits.

The function should limit it to 15, or drop the limit check and document that the user has to make sure to check the limits depending on the context the script is used in.

**Comment by jgriffiths** [comment]
This was a typo, thanks for the report! Fixed in #210.
