### ISSUE TITLE
There are clearly duplicates in the generation of mnemonic bip39

### ISSUE THREAD

**Issue by Milerius** [ElementsProject/libwally-core#172]
Hello it's very possible that I'm doing it wrong, but I have the impression that the mnemonic generation does not work at all

```cpp
        std::string get_mnemonic() {
        std::array<unsigned char, WALLY_SECP_RANDOMIZE_LEN> data;
        assert(WALLY_OK == wally_secp_randomize(data.data(), data.size()));
        char* output;
        words* output_words;
        assert(WALLY_OK == bip39_get_wordlist(NULL, &output_words));
        assert(WALLY_OK == bip39_mnemonic_from_bytes(output_words, data.data(), data.size(), &output));
        assert(WALLY_OK == bip39_mnemonic_validate(output_words, output));
        return output;
}
```

And i have call `wally_init` and `wally_cleanup` correctly in the main function

![image](https://user-images.githubusercontent.com/21139416/73139642-639d7600-4070-11ea-9e6e-3ea364ac6ed6.png)

**Comment by Milerius** [comment]
I have 0 assertion that failed, and in the result there word display twice that's fully broken no ?

**Comment by glslang** [comment]
secp_randomize is used for secp context initializsation not generation of random bytes. wally has no way of generating random bytes that can be used as an input to these functions.
up to the caller to figure out how to do it.

**Comment by greenaddress** [comment]
Closing as the function called expects random data rather than provide for as per @glslang comment.
