### ISSUE TITLE
psbts with 0 outputs should be serializable.

### ISSUE THREAD

**Issue by rustyrussell** [ElementsProject/libwally-core#205]
We are using psbts to hand around our new APIs for merging later.  It's particularly convenient for our new "fundpsbt" to return a set of utxos to spend in psbt form.

Adding a dummy output is awkward: we have have overfunded and the user may want to create a change output, so we'd rather them end up with an invalid tx than accidentally pay a huge fee.

Unfortunately, transaction.c:1986 refuses to allow a zero output tx, so converting our psbt to base64 fails...

**Comment by jgriffiths** [comment]
Fixed in #210.
