### ISSUE TITLE
Could not build Android library on MacOS

### ISSUE THREAD

**Issue by jollyjoker992** [ElementsProject/libwally-core#231]
I tried several times to build the Android library but it's failed by somehow. 
I installed all necessary dependencies for my Mac then run the shell file `tools/build_android_libraries.sh` but it always report the same error:

`clang: error: no such file or directory: './.libs/libwallycore.so'`

It works well on Ubuntu but always get that error on MacOS. 
Can you help on this? 
Thanks.

**Comment by jgriffiths** [comment]
Hi @jollyjoker992 - can you attach the full output of the build? also what is in the src/.libs directory when you get that error?

**Comment by jollyjoker992** [comment]
@jgriffiths Thanks for your reply. 
All files in `/src/.lib` when the error occurred following.
```
libswig_java.a                libwallycore_la-address.o     libwallycore_la-bip32.o       libwallycore_la-ecdh.o        libwallycore_la-internal.o    libwallycore_la-pullpush.o    libwallycore_la-symmetric.o
libswig_java.la               libwallycore_la-aes.o         libwallycore_la-bip38.o       libwallycore_la-elements.o    libwallycore_la-mnemonic.o    libwallycore_la-script.o      libwallycore_la-transaction.o
libwallycore.la               libwallycore_la-base58.o      libwallycore_la-bip39.o       libwallycore_la-hex.o         libwallycore_la-pbkdf2.o      libwallycore_la-scrypt.o      libwallycore_la-wif.o
libwallycore.lai              libwallycore_la-bech32.o      libwallycore_la-blech32.o     libwallycore_la-hmac.o        libwallycore_la-psbt.o        libwallycore_la-sign.o        libwallycore_la-wordlist.o
```

**Comment by jgriffiths** [comment]
Hi, I think your problem is:

````
ls: /System/Volumes/Data/Users/jollyjoker992/android-ndk-r19c/toolchains/llvm/prebuilt/darwin-x86_64/bin/x86-linux-android*19-clang: No such file or directory
````

i.e. theres no support for abi 19 in your installed package. Can you try changing `api="19"` to `api="21"` in `tools/build_android_libraries.sh`?

If that doesn't work can you show the output of `ls /System/Volumes/Data/Users/jollyjoker992/android-ndk-r19c/toolchains/llvm/prebuilt/darwin-x86_64/bin` ?

**Comment by jgriffiths** [comment]
Also note that if you cant build x86 you can build the others, by passing one of `armeabi-v7a arm64-v8a x86_64` to `tools/build_android_libraries.sh`. Your log shows several other targets already build successfully.

**Comment by jollyjoker992** [comment]
@jgriffiths I checked the linux build and it also has that error message but it can pass the build process, so i don't think that is the root cause. My guess is that it cannot pass the ctest with the shared lib with extension `.so` in the macOS, it should be `.dylib` since it switch to use host OS's `gcc` instead of android toolchain.
I explored the Android pre-build C compiler libraries inside the `toolchains` and it only has libraries with prefix `i686` instead of `x86`. I'm using the `android-ndk-r19c`.

**Comment by jgriffiths** [comment]
It seems the update to deprecate make_standalone_toolchain.py is missing a couple of cases. e.g. android_build_wally in tools/android_helpers.sh is missing:

````
x86) clangarchname=i686;;
````

I'll have a look at updating this and verifying a build locally tomorrow.

**Comment by jgriffiths** [comment]
Hi @jollyjoker992 could you try building with the PR in https://github.com/ElementsProject/libwally-core/pull/232 ?

Hopefully this will fix your builds, if not please let me know what error you get. I don't have the tool binaries for MacOS on my Linux install of the NDK so I can't be sure the paths are fully correct - although the script will now exit with an error if any build tool like clang is missing.

**Comment by jollyjoker992** [comment]
@jgriffiths Thanks for your supporting. I will try it today.

**Comment by jollyjoker992** [comment]
@jgriffiths Great job! It works well on my Mac. Thanks for your help. Please consider to merge the PR as soon as you can.

**Comment by jgriffiths** [comment]
Thanks for testing :)

I'll merge it and close this issue shortly, just testing the travis build caching first.

**Comment by jgriffiths** [comment]
Merged, closing.
