### ISSUE TITLE
Multisig psbt input signing not supported?

### ISSUE THREAD

**Issue by Fonta1n3** [ElementsProject/libwally-core#233]
I see this comment: [https://github.com/ElementsProject/libwally-core/blob/master/src/psbt.c#L24](https://github.com/ElementsProject/libwally-core/blob/master/src/psbt.c#L24)

I am using 0.7.7 for now and signing multisig inputs without issue, I would like to confirm that 0.7.9 breaks multisig psbt signing before I attempt to update?

**Comment by jgriffiths** [comment]
Hi @Fonta1n3 : multisig is not broken by later releases, the comment refers to generic multisig as currently only simple multisig scripts can be finalized. The finalization code should be generalised to handle more complicated multisig scripts (such as those with timeout conditions etc) in the future; this is what the FIXME refers to.

In general we try to note all ABI and breaking changes in CHANGES.md, FIXMEs in the code are for internal tracking/notes.

**Comment by Fonta1n3** [comment]
@jgriffiths thank you for the clarification, much appreciated.
