### ISSUE TITLE
The way to figure out the appropriate private key to sign the PSBT

### ISSUE THREAD

**Issue by jollyjoker992** [ElementsProject/libwally-core#235]
I supposedly think that we have to get the `bip32_derivs` from `inputs` to get the appropriate private key for signing the PSBT that has been updated before. Is there any way to do that from the libwally? 
Correct me if anything wrong here. 
Thanks.

**Comment by jgriffiths** [comment]
Hi @jollyjoker992, In C/C++ you can just directly access the keypaths map in the psbt input using the wally_map functions. the accessors for keypaths were not exposed to Python/Java, if you can confirm that is fixed for you by https://github.com/ElementsProject/libwally-core/pull/236 that would be great.

You will need to convert the key paths stored in the inputs into little endian uint32 arrays in order to pass them e.g. to bip32 key derivation functions. The raw data is the 4 byte fingerprint followed by the path elements as little endian 4 byte integers (using struct.pack/unpack this is the format `"<I"`). As noted in the PR commit I hope to add utility functions to make this easier in the future.

**Comment by jollyjoker992** [comment]
@jgriffiths Seems like you only expose for Python? Can you do it for Java?

**Comment by jgriffiths** [comment]
@jollyjoker992 I can expose the psbt interface to java including these functions, but it seems you have already made an attempt at it in https://github.com/jollyjoker992/libwally-core/commit/d2728246b4f3a43c2bd352ce652fe91effe5ccef - given that it seems you could expose these functions also without much effort.

Note that exposing psbt inputs and output objects and their functions as you have done is not really the way psbt is meant to be used; transaction inputs and outputs are added to psbts so really only the map type and psbt should be exposed to java/python.

If you PR your changes to wally in the future I can review them and merge them which will probably save both of us some time.
 In the meantime I will work on exposing to Java correctly but be aware this will conflict with your current master branch.

**Comment by jollyjoker992** [comment]
@jgriffiths Thank for your support and really appreciate your effort.

>Note that exposing psbt inputs and output objects and their functions as you have done is not really the way psbt is meant to be used; transaction inputs and outputs are added to psbts so really only the map type and psbt should be exposed to java/python.

I'm wondering if we do not expose input/output related functions, how can we build the PSBT from the beginning to final? I mean we have to build manually step by step like `Create -> Update -> Sign -> Finalize` without using another tool like `bitcoin-cli`? 
Correct me if i misunderstand anything. Thanks!

**Comment by jgriffiths** [comment]
>I'm wondering if we do not expose input/output related functions, how can we build the PSBT from the beginning to final? I mean we have to build manually step by step like Create -> Update -> Sign -> Finalize without using another tool like bitcoin-cli.
Correct me if i misunderstand anything. Thanks!

We expose the getters and setters on inputs and outputs via the PSBT, just not the input and output structs themselves. Building a PSBT from scratch is done by adding and removing *transaction* inputs/outputs, setting any associated/required data on the corresponding PSBT input/output using the getters/setters, and then calling the psbt functions such as combine/sign etc to manipulate the result. Adding a tx input/output creates the corresponding PSBT input/output in the PSBT which you can then manipulate.

**Comment by jgriffiths** [comment]
@jollyjoker992 I've updated the PR to expose all PSBT functions including getters/setters for PSBT inputs and outputs.

Check out psbt_get_input_keypath_fingerprint and psbt_get_input_keypath_path in particular; these get the bip32 key path from a psbt. They will need to be tested, in particular that the path is correctly converted from little endian.

**Comment by jollyjoker992** [comment]
@jgriffiths Much appreciated. I will check it out and get back to you soon. Thanks!

**Comment by jollyjoker992** [comment]
@jgriffiths I already tested it and it works well on my side. Can you consider to merge it soon? BTW, thanks for your great effort.

**Comment by jgriffiths** [comment]
@jollyjoker992 The PR is merged in master now so closing this. Thanks for testing the changes :)
