### ISSUE TITLE
Handle properly different witness versions with wally_witness_program_from_bytes

### ISSUE THREAD

**Issue by LeoComandini** [ElementsProject/libwally-core#238]
`wally_witness_program_from_bytes` needs to either renamed `wally_witness_v0_program_from_bytes`, or (better) given the `witver` value as a parameter.

Suggested by @roconnor-blockstream

**Comment by jgriffiths** [comment]
Merged `wally_witness_program_from_bytes_and_version` as part of bech32m support, so closing.
