### ISSUE TITLE
Support python 3.8 and 3.9 for python-wallycore in releases

### ISSUE THREAD

**Issue by niftynei** [ElementsProject/libwally-core#239]
Attempting to follow the excellent [suggestion](https://github.com/ElementsProject/lightning/pull/4055#issuecomment-693183233) by @jgriffiths that we use the release imports to add `wallycore` to our project while we're waiting for the Pypi distro to come out. 

However, I can't install it successfully on my dev machine, since I'm currently running Python 3.8.

iiuc the build machines images need to be updated to include/have Python 3.8/3.9 at build time.

**Comment by jgriffiths** [comment]
The next release v0.8.1 will include build for python 3.6, 3.7, 3.8 & 3.9 (artifacts are now being correctly produced by our internal CI), closing.

We will make the 0.8.1 release soon once PyPI wheel uploading is working.
