### ISSUE TITLE
Method to get keypath, fingerprint and pubkey from a wally_map

### ISSUE THREAD

**Issue by Sjors** [ElementsProject/libwally-core#241]
Basically the reverse of `wally_psbt_input_add_keypath_item` and `wally_psbt_output_add_keypath_item`.

**Comment by jgriffiths** [comment]
It might be a while before these are added. For now you will need to manually extract the data - the fingerprint as the first 4 bytes of the value; the remainder of the date is little endian encoded uint32's holding the path.

**Comment by Sjors** [comment]
That's indeed what I ended up doing, rather tedious, and adding a dependency on internal data structures.

https://github.com/blockchain/libwally-swift/pull/45/commits/eac080bddd1c21a1ba41c2064cbfeb062bfcda8d?file-filters%5B%5D=.md&file-filters%5B%5D=.swift#diff-dd5b685bc72957e5736a7a36ebcea752f6c6e49bd4f5a0792b46e6f4cecb9658R20

**Comment by jgriffiths** [comment]
I think you need some logic around `$0.load(as: UInt32.self)` to load as little endian for big endian architectures.

**Comment by jgriffiths** [comment]
These are now available as `wally_map_keypath_get_bip32_key_from_alloc`, `wally_keypath_get_fingerprint`, `wally_map_keypath_get_item_fingerprint`, `wally_keypath_get_path_len`, `wally_map_keypath_get_item_path_len`, `wally_keypath_get_path`, and `wally_map_keypath_get_item_path` from `wally_map.h`.
