### ISSUE TITLE
building with GH actions with clang

### ISSUE THREAD

**Issue by gorazdko** [ElementsProject/libwally-core#245]
## Abstract

Building libwally-core with Github actions on Linux with Clang ([source](https://github.com/gorazdko/libwally-core/blob/master/.github/workflows/ci.yml)):

```bash
  build-Linux_clang:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - run: wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add - || exit 1
    - run: sudo apt-add-repository "deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-10 main" || exit 1
    - run: sudo apt-get update || exit 1
    - run: sudo apt-get install -y clang-10
    - run: export CC="clang-10" && ./tools/autogen.sh && ./configure && make && make check
```
It results in `FAIL: test_clear` (https://github.com/gorazdko/libwally-core/runs/1393233151?check_suite_focus=true)

Is it possible to only disable `pthreads` with `./configure` call to avoid the problem?

**Comment by jgriffiths** [comment]
You can pass --disable-tests to configure to disable the tests, or try a different clang version, let me know if neither works for you.

**Comment by gorazdko** [comment]
I tried with clang 9, 10 and 11. Same error.

Yes I'm aware of `--disable-tests` which I also use on MINGW (with Clang) platform, otherwise the same problem occurs there.

If `--disable-tests` is the only option I'll continue to use it. I would prefer the option to manually disable `pthreads` though.

**Comment by jgriffiths** [comment]
`./configure USE_PTHREAD=no <your configure args>` should work to just disable that test, please let me know if that works for you.

**Comment by gorazdko** [comment]
`./configure USE_PTHREAD=no` had no effect. The same behaviour happens locally on my machine (Ubuntu18.04 + clang)

https://github.com/gorazdko/libwally-core/runs/1449902177?check_suite_focus=true

**Comment by jgriffiths** [comment]
Hi @gorazdko sorry for the delay. Could you verify that https://github.com/ElementsProject/libwally-core/pull/252 fixes the build for you?

If test_clear still doesn't pass with these changes you can pass `--enable-clear-tests` to skip just that test. Please let me know whether you require that workaround.

**Comment by gorazdko** [comment]
This works for me. Thanks!

**Comment by jgriffiths** [comment]
@gorazdko good to hear, thanks for reporting back :)
