### ISSUE TITLE
Wasm: bip39_mnemonic_to_seed returns wrong seed

### ISSUE THREAD

**Issue by Sosthene00** [ElementsProject/libwally-core#258]
I'm using the [test vectors for bip39](https://github.com/trezor/python-mnemonic/blob/master/vectors.json) against some code I wrote using the wasm build of libwally. 
The first case produces a wrong seed and xprv.
Expected is 
```
"00000000000000000000000000000000",
"abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about",

"c55257c360c07c72029aebc1b53c05ed0362ada38ead3e3e9efa3708e53495531f09a6987599d18264c1e1c92f2cf141630c7a3c4ab7c81b2f001698e7463b04",

"xprv9s21ZrQH143K3h3fDYiay8mocZ3afhfULfb5GX8kCBdno77K4HiA15Tg23wpbeF1pLfs1c5SPmYHrEpTuuRhxMwvKDwqdKiGJS9XFKzUsAF"
```

What I obtain is: 
```
"00000000000000000000000000000000",
"abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about", // this is ok

"5eb00bbddcf069084889a8ab9155568165f5c453ccb85e70811aaed6f6da5fc19a5ac40b389cd370d086206dec8aa6c43daea6690f20ad3d8d48b2d2ce9e38e4", // this is not

"xprv9s21ZrQH143K3GJpoapnV8SFfukcVBSfeCficPSGfubmSFDxo1kuHnLisriDvSnRRuL2Qrg5ggqHKNVpxR86QEC8w35uxmGoggxtQTPvfUu" // this neither
```

Here's my code:
* I have a function written in C:
```
char *generateSeed(const char *mnemonic) {
    int ret;
    size_t written;
    unsigned char seed[BIP39_SEED_LEN_512];
    char *seed_hex;

    if ((ret = bip39_mnemonic_to_seed(mnemonic, NULL, seed, sizeof(seed), &written)) != 0) {
        printf("bip39_mnemonic_to_seed failed with %d error code\n", ret);
        return "";
    }

    if (written != BIP39_SEED_LEN_512) {
        printf("seed is not %d long, but %lu", BIP39_SEED_LEN_512, (unsigned long)written);
        return "";
    }

    wally_hex_from_bytes(seed, sizeof(seed), &seed_hex);
    return seed_hex;
}
```
* that I call from js like this
```
if ((seed_hex = ccall('generateSeed', 'string', ['string'], [mnemonic])) === "") {
      console.log("generateSeed failed");
      return "test_generateSeed KO: generateSeed failed";
    }
```

All the other test cases are allright, so there must be something specific about having a 16B all 0s entropy. I test the mnemonic against the test vector and it's the same, so the issue must be with the seed generation.

[EDIT] I checked that libwally prng is initialized, but it doesn't change the outcome

[EDIT] Actually there was an issue with my test (yeah I know I'm a js rookie), all the cases fail, which is better somehow I guess, it means I must have gotten something wrong with seed generation

**Comment by Sosthene00** [comment]
Ok actually it might be something wrong with the way I make my test, I just noticed that if I erase the first case, then the 2nd one fails in the same way (mnemonic is ok, the rest is not)

**Comment by jgriffiths** [comment]
Hi @Sosthene00 we are happy to try to investigate and fix any issues with the library, but please be aware that our time is currently very over-subscribed. We can't currently afford time to help you debug your code/tests. Also note that the wasm interface is marked as experimental, so it is not as high priority as a bug found in e.g. the underlying C code.

Can I ask you, if you think you have found a bug, to investigate it, write up the shortest possible example demonstrating the bug and include what circumstances (if any) it doesn't happen under. I don't want to discourage you from submitting bug reports, or from hacking on code using wally, but you would help us out greatly if you can reduce the amount of time we spend looking at issues that are not in fact bugs.

Closing this for now, if you can create a simple test case demonstrating a bug please re-open and attach it, thanks :)

**Comment by Sosthene00** [comment]
Hi, sorry I didn't mean to abuse your time. I won't notice you further unless I suspect an issue with Libwally codebase.

**Comment by Sosthene00** [comment]
For anyone that might stumble on this issue one day: the seed generated from the mnemonic was not the same because the test vectors [here](https://github.com/trezor/python-mnemonic/blob/master/vectors.json) imply that you use the passphrase "TREZOR" for all cases. 

So definitely not an issue with Libwally, not even with the code I write, only with my own inability to RTFM.

**Comment by jgriffiths** [comment]
@Sosthene00 Thanks for updating!
