### ISSUE TITLE
Please provide wally_cleanup() (?) to clear internal allocations.

### ISSUE THREAD

**Issue by rustyrussell** [ElementsProject/libwally-core#26]
In particular, my tests complain about a memory leak because you allocate a secp ctx.  Unf. that allocator isn't switchable, so I can't even hack it that way.

**Comment by jgriffiths** [comment]
@rustyrussell I've added wally_cleanup() as requested.

I've also added wally_get_secp_context() so you can share the same context as wally. You may also want to add a call to either wally_secp_randomize/secp256k1_context_randomize at app/daemon startup.
