### ISSUE TITLE
Compile on windows

### ISSUE THREAD

**Issue by PayteR** [ElementsProject/libwally-core#261]
Hi, i want to use `libwally` code in my project on windows, but I'm new into C language, could you point me, how to compile `libwally` so that i can use *.lib files from with static linking? 

I tried `Cygwin`, but i couldn't compile project
```
$ ./tools/autogen.sh
./tools/autogen.sh: line 2: autoreconf: command not found
./tools/autogen.sh: line 5: syntax error near unexpected token `$'do\r''
'/tools/autogen.sh: line 5: `    for f in ./tools/build-aux/ltmain.sh ./src/secp256k1/build-aux/ltmain.sh; do

$ ./configure --enable-debug --enable-export-all --enable-swig-python --enable-swig-java --enable-coverage
-bash: ./configure: No such file or directory

$ make
mingw32-make: *** No targets specified and no makefile found.  Stop.
````
thx

**Comment by jgriffiths** [comment]
Hi,

`tools/msvc/build.bat` builds wally with the ms complier, and should be tweakable to produce a tatic lib instead of a dll.

Otherwise you can either include the source files directly in your project (painful) or cross compile.

**Comment by PayteR** [comment]
It doesn't work 

```
set LIBWALLY_DIR=D:\dotnet\SeedcrackerCpp\libwally-core\tools\msvc

REM Need to first build gen_context.exe to generate a header file

REM It seems possible to skip this step and remove the definition

REM of USE_ECMULT_STATIC_PRECOMPUTATION  from the compiler flags

call "D:\dotnet\SeedcrackerCpp\libwally-core\tools\msvc\\gen_ecmult_static_context.bat"

cl /utf-8 /DWALLY_CORE_BUILD /DHAVE_CONFIG_H /DSECP256K1_BUILD /ID:\dotnet\SeedcrackerCpp\libwally-core\tools\msvc\src\wrap_js\windows_config /ID:\dotnet\SeedcrackerCpp\libwally-core\tools\msvc\ /ID:\dotnet\SeedcrackerCpp\libwally-core\tools\msvc\src /ID:\dotnet\SeedcrackerCpp\libwally-core\tools\msvc\include /ID:\dotnet\SeedcrackerCpp\libwally-core\tools\msvc\src\ccan /ID:\dotnet\SeedcrackerCpp\libwally-core\tools\msvc\src\secp256k1 /Zi D:\dotnet\SeedcrackerCpp\libwally-core\tools\msvc\src/secp256k1/src/gen_context.c /Fegen_context.exe
'cl' is not recognized as an internal or external command,
operable program or batch file.

gen_context.exe
'gen_context.exe' is not recognized as an internal or external command,
operable program or batch file.

REM There are duplicate file names in both the wally and ccan sources

REM In a sane build system this would not be a problem but because

REM everything is being munged together for Windows as a hack it causes

REM problems. Make renamed copies as a workaround.

copy src\ccan\ccan\str\hex\hex.c src\ccan\ccan\str\hex\hex_.c
The system cannot find the path specified.

copy src\ccan\ccan\base64\base64.c src\ccan\ccan\base64\base64_.c
The system cannot find the path specified.
( was unexpected at this time.
if  == "elements" (
```

**Comment by PayteR** [comment]
> Hi,
> 
> `tools/msvc/build.bat` builds wally with the ms complier, and should be tweakable to produce a tatic lib instead of a dll.
> 
> Otherwise you can either include the source files directly in your project (painful) or cross compile.
```
set LIBWALLY_DIR=D:\projects\libwally-core\tools\msvc

REM Need to first build gen_context.exe to generate a header file

REM It seems possible to skip this step and remove the definition

REM of USE_ECMULT_STATIC_PRECOMPUTATION  from the compiler flags

call "D:\projects\libwally-core\tools\msvc\\gen_ecmult_static_context.bat"

cl /utf-8 /DWALLY_CORE_BUILD /DHAVE_CONFIG_H /DSECP256K1_BUILD /ID:\projects\libwally-core\tools\msvc\src\wrap_js\windows_config /ID:\projects\libwally-core\tools\msvc\ /ID:\projects\libwally-core\tools\msvc\src /ID:\projects\libwally-core\tools\msvc\include /ID:\projects\libwally-core\tools\msvc\src\ccan /ID:\projects\libwally-core\tools\msvc\src\secp256k1 /Zi D:\projects\libwally-core\tools\msvc\src/secp256k1/src/gen_context.c /Fegen_context.exe
'cl' is not recognized as an internal or external command,
operable program or batch file.

gen_context.exe
'gen_context.exe' is not recognized as an internal or external command,
operable program or batch file.

REM There are duplicate file names in both the wally and ccan sources

REM In a sane build system this would not be a problem but because

REM everything is being munged together for Windows as a hack it causes

REM problems. Make renamed copies as a workaround.

copy src\ccan\ccan\str\hex\hex.c src\ccan\ccan\str\hex\hex_.c
The system cannot find the path specified.

copy src\ccan\ccan\base64\base64.c src\ccan\ccan\base64\base64_.c
The system cannot find the path specified.
( was unexpected at this time.
if  == "elements" (
```

**Comment by jgriffiths** [comment]
You can see it working here https://github.com/ElementsProject/libwally-core/runs/1683652030?check_suite_focus=true

Please look at the sequence of dependency installs and building actions in https://github.com/ElementsProject/libwally-core/blob/master/.github/workflows/wheels.yml which the windows release build is made from.

**Comment by PayteR** [comment]
Hm there are some problems, first is that in `build.bat` is `set LIBWALLY_DIR=%cd%` which is current directory of that bat file, correct path is `set LIBWALLY_DIR=%cd%/../../`

Second problem that i didn't solved for hours is this
```
D:\projects\libwally-core\src\secp256k1\include/secp256k1.h(8): fatal error C1083: Cannot open include file: 'stddef.h': No such file or directory
```
When i try to compile any example code with `stddef.h` header in VS2019 it runs well, but when i try to use any cl.exe from VC directory, then this problem occurss

**Comment by PayteR** [comment]
When i try to use `act` https://github.com/nektos/act to compile it by workflow, ten there is this error

```
PS D:\projects\libwally-core> act
←[34m[Build/Build wheels on macos-latest-2  ] ←[0m🚧  Skipping unsupported platform '[${{ matrix.os }}]'
←[33m[Build/Build wheels on windows-latest-1] ←[0m🚧  Skipping unsupported platform '[${{ matrix.os }}]'
```

**Comment by jgriffiths** [comment]
I clearly says on that projects `README.md` that neither windows or mac are supported.

**Comment by PayteR** [comment]
> It clearly says on that projects `README.md` that neither windows or mac are supported.

Which projects do you mean? Because `act` supports windows, and this project  `README.md` said:

```
Wally can currently be built for:

Linux
Android
macOS
iOS
Windows
WebAssembly
```

**Comment by jgriffiths** [comment]
Look under 'Runners' in that document.

**Comment by PayteR** [comment]
> Look under 'Runners' in that document If you build using github CI you can take the build results and use that in your code, if you are unable to build it yourself.

ah this... :-/

> We aren't able to provide support for building wally statically on windows however, its not currently a supported release target.

you said above 

> tools/msvc/build.bat builds wally with the ms complier, and should be tweakable to produce a tatic lib instead of a dll.

But `cl.exe` is not working for me because of that  `Cannot open include file: 'stddef.h'` problem. When i solve this problem, then this `build.bat` will compile `*.lib` files? Because that's my goal. I want to include this lib files and header files in my project and use some function for generating public key from mnemonic for example.

**Comment by jgriffiths** [comment]
> But cl.exe is not working for me because of that Cannot open include file: 'stddef.h' problem.

googling `msvc Cannot open include file: 'stddef.h'` provides plenty of potential solutions to this issue.

> When i solve this problem, then this build.bat will compile *.lib files?

According to the `link.exe` documentation, it will usually build a .lib file when linking into a .dll file. Using the compiler to produce libraries is out of the scope of issues for this project however, if you need help please see the MS documentation.

**Comment by PayteR** [comment]
I already googled that error message and didn't get the answer to my issue with cl.exe, most of the answers was related to the Qt framework, or missing SDK, but I'm sure that i have that SDK and when i include stddef.h in some example VS2019 project everything is fine. 

I know that my questions sounds lame, but I'm lost now when i can't run build.bat that should be configured to run on W10. Should i try to use another compiler with cl.exe instead of that from VS2019? Or i need to add another parameter with SDK include path? Thank you for your help

**Comment by jgriffiths** [comment]
@PayteR I am not able to provide support on how to use the MS compiler I'm afraid, this isn't the place for that.

There is a working example that builds the windows release using the batch files so we know there is no bug in the library that needs fixing.

Like any issue, you should try to make the smallest test case that fails. Can you compile a single small C file that includes stddef.h? If not then please use an appropriate support channel for the compiler to get that working - you will probably find that fixing this issue gets you further.

I wish you luck in learning C coding, although I'm unable to provide support for it I hope you persevere and find great enjoyment coding!
