### ISSUE TITLE
Sign a message with `wally_ec_sig_from_bytes` produces a signature that doesn't verify with Elements `verifymessage`

### ISSUE THREAD

**Issue by Sosthene00** [ElementsProject/libwally-core#266]
I'm trying to produce a signature for a given arbitrary message and pubkey that verifies with Elements' `verifymessage` command.

Let's say:
```
unsigned char message[]; // "e803ba4ff3b8ad4e85d2415f93937ef90d20f5c55bebd641c02a045ba604f8a4"
unsigned char signingKey[EC_PRIVATE_KEY_LEN]; // 2a080f92fa38bad1df98c21bb3afd531970c11d9f00048950fd003d227279f32
```
The (elementsregtest) address that corresponds to this private key is `2daQFL6hJYFoobEaVURBxPBFaBKMQYPAoa8`, the pubkey is `02953f48c8c8839149319d98f7d359b22eb2d0da9a6aa5e57e9b3a774c7b225381`.

I first format my message with `wally_format_bitcoin_message`:
```
wally_format_bitcoin_message(message, sizeof(message), BITCOIN_MESSAGE_FLAG_HASH, hash, sizeof(hash), &written);
```
I take the hash it returns and sign it with `wally_ec_sig_from_bytes`:
```
wally_ec_sig_from_bytes(signingKey, EC_PRIVATE_KEY_LEN,
                                        hash, EC_MESSAGE_HASH_LEN, 
                                        EC_FLAG_ECDSA | EC_FLAG_RECOVERABLE | EC_FLAG_GRIND_R,
                                        sig, sig_len)) != 0)
```
I get this signature: `1f269eefd90876a82dd2a7563c54f0a3cf422c2e20d17664b9a8d7760f9f9b75b41b51a39449c288cfd96dd9ba88bfe4a2f6bfd1e23fa88315029c76ac9e71111c` or `Hyae79kIdqgt0qdWPFTwo89CLC4g0XZkuajXdg+fm3W0G1GjlEnCiM/Zbdm6iL/kova/0eI/qIMVApx2rJ5xERw=`
Now I want to verify it in Elements:
```e1-cli verifymessage "2daQFL6hJYFoobEaVURBxPBFaBKMQYPAoa8" "Hyae79kIdqgt0qdWPFTwo89CLC4g0XZkuajXdg+fm3W0G1GjlEnCiM/Zbdm6iL/kova/0eI/qIMVApx2rJ5xERw=" "e803ba4ff3b8ad4e85d2415f93937ef90d20f5c55bebd641c02a045ba604f8a4"```
and this is false.
I tried to verify it with Libwally:
`wally_ec_sig_to_public_key(message, sizeof(message), sig, sizeof(sig), pubkey, sizeof(pubkey));`
The function returns `WALLY_OK`, but I'm a bit puzzled because the pubkey I get from this is `030970c24022584f62d5cf36360d224e6c9fbc9d1a6fd44bfe7f443a18745f6674`, which is not the pubkey I expected.

Is it really expected, or is there an issue with either the signature or the verification? Are Libwally made signatures compatible with Elements?

You can run it and see all those results by downloading the files below in the same dir, launch a python server and open the `.html` file in the browser:
`wget https://raw.githubusercontent.com/chainaccelerator/contribox-client-multisign/elements_compatible_sig/bin/contribox.html`
`wget https://raw.githubusercontent.com/chainaccelerator/contribox-client-multisign/elements_compatible_sig/bin/contribox.js`
`wget https://raw.githubusercontent.com/chainaccelerator/contribox-client-multisign/elements_compatible_sig/bin/contribox.wasm`
`wget https://raw.githubusercontent.com/chainaccelerator/contribox-client-multisign/elements_compatible_sig/bin/main.js`

**Comment by LeoComandini** [comment]
Hi @Sosthene00,

Both the Elements node and wally fail to verify the signature (with 
`wally_ec_sig_to_public_key`, _"The successful recovery of the public key 
guarantees the correctness of the signature."_).
Thus the issue might be that message was encoded differently when signing and when 
verifying. For instance in python we must use `str.encode('ascii')`.

```
import wallycore as wally
import base64

h2b = wally.hex_to_bytes
b2h = wally.hex_from_bytes

def sign_message(private_key, message):
    h = wally.format_bitcoin_message(message.encode('ascii'), wally.BITCOIN_MESSAGE_FLAG_HASH)
    flags = wally.EC_FLAG_ECDSA | wally.EC_FLAG_RECOVERABLE
    recoverable_signature = wally.ec_sig_from_bytes(private_key, h, flags)
    return base64.b64encode(recoverable_signature).decode()

def pub_to_p2pkh_address(pub: bytes) -> str:
    scriptpubkey = wally.scriptpubkey_p2pkh_from_bytes(pub, wally.WALLY_SCRIPT_HASH160)
    network = wally.WALLY_NETWORK_LIQUID_REGTEST
    return wally.scriptpubkey_to_address(scriptpubkey, network)

def verify_message(address, signature, message):
    h = wally.format_bitcoin_message(message.encode('ascii'), wally.BITCOIN_MESSAGE_FLAG_HASH)
    recoverable_sig = base64.b64decode(signature)
    pub = wally.ec_sig_to_public_key(h, recoverable_sig)
    return pub_to_p2pkh_address(pub) == address

prv_hex = "2a080f92fa38bad1df98c21bb3afd531970c11d9f00048950fd003d227279f32"
msg_str = "e803ba4ff3b8ad4e85d2415f93937ef90d20f5c55bebd641c02a045ba604f8a4"

prv = h2b(prv_hex)
pub = wally.ec_public_key_from_private_key(prv)
address = pub_to_p2pkh_address(pub)

assert pub == h2b("02953f48c8c8839149319d98f7d359b22eb2d0da9a6aa5e57e9b3a774c7b225381")
assert address == "2daQFL6hJYFoobEaVURBxPBFaBKMQYPAoa8"

sig_b64 = sign_message(prv, msg_str)
assert verify_message(address, sig_b64, msg_str)

print(f"elements-cli verifymessage {address} {sig_b64} {msg_str}")
```

```
$ elements-cli verifymessage 2daQFL6hJYFoobEaVURBxPBFaBKMQYPAoa8 H7YG7/eZSnQIKGKIt75ewDTOkiM2kyvKTN4m1pURJiIUaDi8A3kSGrr47/2Czn7RhJX91xlrf0EfReooJEzokek= e803ba4ff3b8ad4e85d2415f93937ef90d20f5c55bebd641c02a045ba604f8a4
true
```

**Comment by Sosthene00** [comment]
Thanks for the sample code @LeoComandini, reading your example made me realize that as my intent was to sign a hex representation of a hash, I was processing the `message` as the bytes sequence encoded in the hex string, and not as a literal string, which resulted in a different hash being signed. It was indeed much clearer in Python than in C.

**Comment by LeoComandini** [comment]
`wally_ec_sig_to_public_key` shouldn't fail, in that case; it computes
(recovers) _a_ pubkey from the message and signature, if that pubkey matches the 
signer pubkey, then the signature is valid for the message and the singer 
pubkey. If the message is changed, as you previously did, 
`wally_ec_sig_to_public_key` will correctly (`WALLY_OK`) recover another pubkey,
but that won't match the signer ones, thus the signature isn't valid for the
changed message and signer pubkey.

**Comment by Sosthene00** [comment]
Ok, but then maybe the man for `wally_ec_sig_to_public_key` is a bit misleading when it says `The successful recovery of the public key guarantees the correctness of the signature.`, I misunderstood this as meaning "it will fail to recover _any_ public key if the signature is false".

Anyway, thanks for the answer!
