### ISSUE TITLE
Make s2c optional

### ISSUE THREAD

**Issue by Sjors** [ElementsProject/libwally-core#299]
It's currently not possible to build with vanilla secp256k1 (see #298), because of the dependency on `secp256k1_ecdsa_s2c.h` introduced in #259.

Having a configure option like `--enable-anti-klepto` would make that dependency optional.

**Comment by jgriffiths** [comment]
@Sjors can you try https://github.com/ElementsProject/libwally-core/pull/301 and comment there if it works for you, thanks
