### ISSUE TITLE
Bech32 & segwit address support

### ISSUE THREAD

**Issue by afk11** [ElementsProject/libwally-core#3]
I've been reviewing for common libraries that may not yet have segwit address support. I haven't seen anyone work on it yet, please add this soon!

https://github.com/bitcoin/bips/blob/master/bip-0173.mediawiki
See also: https://github.com/sipa/bech32/tree/master/ref/c

**Comment by greenaddress** [comment]
@afk11 yep, it's planned but thanks for ping!

**Comment by jonathancross** [comment]
Hi @afk11 Is this still feature under development?

I'm looking for a clean python implementation that can handle BIP39 seed phrases and `P2WPKH-in-P2SH` (with `m/49'/0'/0'/0/0` BIP32 path).  I can probably extract what I need from Electrum, but thought I'd try here first.

**Comment by jgriffiths** [comment]
Hi, I've just added segwit address support using sipas reference encoder. At some point in the future we will probably expose the underlying bech32 api (e.g. for c-lightning), but for now its a high level api for BTC only.

**Comment by jonathancross** [comment]
Hi @jgriffiths  I don't see `P2WPKH-in-P2SH`, did I miss it? Or is there a plan to add it at some point?
