### ISSUE TITLE
iOS build example

### ISSUE THREAD

**Issue by tiero** [ElementsProject/libwally-core#30]
Hi!

It's possible to have some example on how to build and include the native binaries in an iOS/ObjectiveC app?

Thank you in advance

**Comment by greenaddress** [comment]
We are working on a native iOS app (open source) which can be used as an example that should satisfy your build instructions requirement but it won't be ready for a while more.

Meanwhile we have an already published JS/Cordova based iOS app which also uses the library (although via JS bindings) that you can see here https://github.com/greenaddress/walletcordova - if you have questions about it please let us know

**Comment by tiero** [comment]
Thank you very much!

PS: maybe isn't correlated, but if I launch the `./tools/autogen.sh` script  

It says that are missing ltmain.sh and other files

```

./tools/autogen.sh: line 2: autoreconf: command not found
sed: ./tools/build-aux/ltmain.sh: No such file or directory
sed: ./tools/build-aux/ltmain.sh: No such file or directory
sed: ./src/secp256k1/build-aux/ltmain.sh: No such file or directory
sed: ./src/secp256k1/build-aux/ltmain.sh: No such file or directory
```

there is something I'm missing in my env?

`gcc --version`

```
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 9.0.0 (clang-900.0.39.2)
Target: x86_64-apple-darwin17.2.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by glslang** [comment]
You'll need to install brew and autotools or some other equivalent to provide all of that.

**Comment by tiero** [comment]
I think can be helpful for others:

using g++, my configure options:
```
$ ./configure --disable-shared --enable-elements --host=armv7-apple-darwin --build=x86_64-apple-darwin --with-sysroot=$(xcrun --sdk iphoneos --show-sdk-path)    --enable-static --prefix=$(pwd)/build
```
