### ISSUE TITLE
CHANGES.md is missing a changelog for 0.8.3 and 0.8.4

### ISSUE THREAD

**Issue by benma** [ElementsProject/libwally-core#306]
See https://github.com/ElementsProject/libwally-core/blob/e4b62491b6fcc19f53f4cef4919ec11db62f518d/CHANGES.md

Would be great to document the changes and anything to look out for when upgrading.

**Comment by jgriffiths** [comment]
Hi @benma 

We only document ABI and build changes in `CHANGES.md`. The releases contain a list of new features per-release, and the git logs are the canonical source of all changes. Per `README.md` - "Note that library interfaces may change slightly while the library design matures. Please see the CHANGES.md file to determine if the API has changed when upgrading.".

There are no ABI changes for the last 2 releases, just fixes and new features.

**Comment by benma** [comment]
Oh I see, thanks!
