### ISSUE TITLE
Can't install pre-built wheels on Max OSX M1 chip python v3.8.9

### ISSUE THREAD

**Issue by niftynei** [ElementsProject/libwally-core#311]
Trying to install the pre-built v0.8.4 libwally wheel on a brand new macbook (m1 chip). Getting this error.

```
<redacted>r@Roberts-MacBook-Pro Downloads % pip3 install wallycore-0.8.4-cp39-cp39-macosx_10_9_x86_64.whl 
Defaulting to user installation because normal site-packages is not writeable
ERROR: wallycore-0.8.4-cp39-cp39-macosx_10_9_x86_64.whl is not a supported wheel on this platform.
```

**Comment by jgriffiths** [comment]
IIUC the M1 is an arm chip so the `x86_64` wheel is the wrong arch. We should pick up support for M1 when we upgrade cibuildwheel to the latest version. I tried this last release but there was a windows build issue holding us back.

I will retry again for the 0.8.5 release, in the meantime you'll need to build this locally (`brew install gnu-sed swig automake` and then `pip install .` from a clean source tree).

**Comment by jgriffiths** [comment]
Closing, release 0.8.5 contains `arm64` and `universal2` wheels which work on M1 archs.
