### ISSUE TITLE
Fail wally_scrypt() when called with an invalid output key size

### ISSUE THREAD

**Issue by shesek** [ElementsProject/libwally-core#345]
When `wally_scrypt()` is called with an invalid key output size (not a power of two, <32 or >(2^32 - 1) * 32), a `WALLY_OK` and an all-zeroed key is returned rather than an error.

This seems like a potential footgun, would be better if it errored with `WALLY_EINVAL` instead.

**Comment by jgriffiths** [comment]
Fixed in https://github.com/ElementsProject/libwally-core/pull/343, thanks for reporting!
