### ISSUE TITLE
v0.8.7 docs missing

### ISSUE THREAD

**Issue by Sjors** [ElementsProject/libwally-core#361]
https://wally.readthedocs.io/ is still at 0.8.6

**Comment by jgriffiths** [comment]
Updated, thanks for the heads up @Sjors

**Comment by Sjors** [comment]
@jgriffiths 0.8.8 docs nag...

**Comment by Sjors** [comment]
The docs are there under "latest", but not under the 0.8.8 path.

**Comment by jgriffiths** [comment]
Updated, readthedocs takes a while before it sees the new release tag and I can build.
