### ISSUE TITLE
psbt creation from scratch?

### ISSUE THREAD

**Issue by Fonta1n3** [ElementsProject/libwally-core#404]
Im using Sjoors wrapper, Libwally-swift, and was wondering if Libwally-core allows creation of a psbt from scratch? In the wrapper all I can do is pass it a psbt in order to init a psbt. 

For example can I init `psbtInputs` and `psbtOutputs` and use them to init a psbt?

**Comment by jgriffiths** [comment]
Hi @Fonta1n3 wally itself allows creating an empty psbt and then adding inputs and outputs, yes. I would also like to add the ability to create a partially-initialized psbt from a tx at some point.

Can I suggest you ask @Sjors to consider extending the swift wrapper to expose the calls you are looking for?

**Comment by Fonta1n3** [comment]
Absolutely, I did that originally, he wasn't sure which is why I am asking here.

Appreciate the response and will try and get this working.

**Comment by jgriffiths** [comment]
No problem, I will close this issue. Please re-open with details if there is a specific call or functionality needed by the swift wrapper, thanks.
