### ISSUE TITLE
bip 44

### ISSUE THREAD

**Issue by tiero** [ElementsProject/libwally-core#44]
There are some plans on adding some functions to help to organize the logical hierarchy of HD wallets with accounts/sub-accounts as in BIP44? Or this should be done in specific implementation outside libwally?

**Comment by jgriffiths** [comment]
Hi,

BIP 44 merely gives a path derivation to be used with BIP 32. As such there is really nothing to support within wally itself; you can pass a BIP 44 (or any other) path to the BIP 32 functions to derive the keys you would use with BIP 44 trivially.
