### ISSUE TITLE
 Problem with results generated from “bip32_key_from_parent_path_alloc”

### ISSUE THREAD

**Issue by 776a7a68616f** [ElementsProject/libwally-core#461]
Hello ！

Thank you for your team's contribution. I seem to have found a serious problem. Please confirm.

The result obtained using bip32_key_from_parent_path does not match the expected outcome.

Using the mnemonic phrase:
"behind mirror pond finish borrow wood park foam guess mail regular reflect"
I can obtain the correct root key and chain code. However, bip32_key_from_parent_path does not return the correct extended account.

When I set:
uint32_t path_account[] = {0};

and call:
bip32_key_from_parent_path_alloc(key_root, path_account, sizeof(path_account), BIP32_FLAG_KEY_PRIVATE, &key_account);
bip32_key_to_base58(key_account, BIP32_FLAG_KEY_PRIVATE, &a_xprv);
the generated result is:

xprvA1dcpzmUUQa2Cuw6G5diH1RpTgQ74fVDs5P3exWCxvn24URJAfiEX59Mgx1A4X22JRaJGVrFAs5KrPtqMPpCeVgTxZ9SJzLF3RD3ZfueVj8

while the expected correct result is:
xprv9vB1ZqiYKRTRQnJuEDY7JvQnH9KnVgqhZoRtrQpRqn7Ay6Gb5BfDy6Mmgp9HvNaH2TqRXHuXC1yh4A1iuUThXHbQ3ndJSG1u5uJb43b3REV.
You can test this on the website: https://iancoleman.io/bip39/

After checking the source code, it seems that the child_num is not added to the end of msg when calculating hmac_sha512. Please check if it is correct.

Thanks ！ 😊

**Comment by jgriffiths** [comment]
Hi,

I don't see this behaviour, the following python test passes without problems:

```
root_xpriv = 'xprv9s21ZrQH143K2X216zEzV2qyJeEWQrnR9HDBAAH5UU5qEyW2CuVR6Fh7F3B5cuvJqQc2Qvx2WnxUZ6TQz1qdmg8jxdAbJFLVu9uKBUNYnz5'
root_key = bip32_key_from_base58(root_xpriv)

derived_key = bip32_key_from_parent_path(root_key, [0], BIP32_FLAG_KEY_PRIVATE)
expected = 'xprv9vB1ZqiYKRTRQnJuEDY7JvQnH9KnVgqhZoRtrQpRqn7Ay6Gb5BfDy6Mmgp9HvNaH2TqRXHuXC1yh4A1iuUThXHbQ3ndJSG1u5uJb43b3REV'

assert bip32_key_to_base58(derived_key, BIP32_FLAG_KEY_PRIVATE) == expected
```

> bip32_key_from_parent_path_alloc(key_root, path_account, sizeof(path_account), 

I suspect you want `sizeof(path_account) / sizeof(path_account[0])` here, you are deriving using more path than you have provided.

**Comment by 776a7a68616f** [comment]
Thank you for your reply. Yes, you are right; I should use “sizeof(path_account) / sizeof(path_account[0])”. I apologize for taking up your time due to my own issues, and I look forward to your continued success.😊
