### ISSUE TITLE
Scrypt support

### ISSUE THREAD

**Issue by btcontract** [ElementsProject/libwally-core#5]
Can I use this library to have native Scrypt support in my android app?
If yes, what should be done to enable it as by default `bitcoinj`s `native_library_loaded = loader.load("scrypt", true);` returns false and uses slow java version of Scrypt when I have `libscrypt.so` replaced with `libwallycore.so`.

Thanks!

**Comment by jgriffiths** [comment]
Hi,

Yes, you can build the library natively for Android and then call the optimised scrypt from Java. Please see https://github.com/GreenAddress/GreenBits which includes the build machinery to build and include the native binaries in the app, and see app/src/main/java/com/greenaddress/greenbits/ui/MnemonicHelper.java for an actual working call to scrypt.
