### ISSUE TITLE
Support BIP 174 PSBT

### ISSUE THREAD

**Issue by achow101** [ElementsProject/libwally-core#53]
It would be nice for libwally to support BIP 174 PSBTs.

**Comment by jgriffiths** [comment]
Hi @achow, we would very much like to have support for 174!

It may be a little while before we can make a start on this however. If you know of any representative implementations that we can use to think about the design, feel free to link them here.

**Comment by nvk** [comment]
+1

**Comment by greenaddress** [comment]
PSBT is now implemented - Closing!
