### ISSUE TITLE
Clarify BIP-Schnorr support

### ISSUE THREAD

**Issue by ysangkok** [ElementsProject/libwally-core#88]
It seems like Libwally supports the broken 2016 Schnorr implementation:

    /** Indicates that a signature using EC-Schnorr-SHA256 is required */
    #define EC_FLAG_SCHNORR 0x2

I assume this is totally incompatible with BIP-Schnorr, and that another flag would be required?

**Comment by greenaddress** [comment]
@ysangkok I don't believe that flag is currently used anywhere and indeed the reference is to the old 2016 broken implementation, this seems just a left over from earlier days. Thus, given it is unused I am not sure if we will need to use a new flag or reuse this one but seems like we could simply reuse it.

**Comment by jgriffiths** [comment]
Thid flsg will be used for BIP-Schnorr sig (and the comment updated) when they are implemented.
