### ISSUE TITLE
ObjC - Elements build cannot reach what after #ifdef BUILD_ELEMENTS

### ISSUE THREAD

**Issue by tiero** [ElementsProject/libwally-core#90]
HI! I built libwally for iOS/ObjC passing the `--enable-elements` flag using 0.6.8 commit.

Once static libs and header included in a iOS project, I cannot reach `wally_confidential_addr_to_addr`, `wally_confidential_addr_to_ec_public_key`, `wally_confidential_addr_from_addr`

If I try to run `wally_is_elements_build` it returns 1, saying elements have been included correctly. 

What I'm doing wrong?

**Comment by glslang** [comment]
hi. can't say what's wrong with your code but I suggest looking at https://github.com/Blockstream/gdk where wally is built for iOS and where all the functions are usable from swift.

**Comment by tiero** [comment]
> hi. can't say what's wrong with your code but I suggest looking at https://github.com/Blockstream/gdk where wally is built for iOS and where all the functions are usable from swift.

yeah, I looked at that, but I cannot find where wally_elements.h is imported or where confidential utils have been used. So still wonder if something objC related. I'll try also swift as check

**Comment by glslang** [comment]
wally_elements is not imported in the public repo although the functions you mention are in wally_address.h and that is in the module.map inside src directory.
