### ISSUE TITLE
2e1f99d0f27911ce2a1869598ff59ee49e68b28e broke wally_get_secp_context()

### ISSUE THREAD

**Issue by rustyrussell** [ElementsProject/libwally-core#95]
Not clear why the type was change to the (undefined!) `struct secp256k1_context`; did you mean just `secp256k1_context` which is a typedef?

**Comment by greenaddress** [comment]
this was fixed in release 0.6.9 (specifically commit b2cde0e528f4e8c60759329fe9958e1eb02b2c69)

See related PR for lightning to remove the workaround
https://github.com/ElementsProject/lightning/pull/2589

Thanks!

Closing
